services:
  - type: web
    name: flask-auth
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python auth/app.py
    plan: free

  - type: web
    name: fastapi-events
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
